### ISSUE TITLE
Could not find imported module support code

### ISSUE THREAD

**Issue by Kariton** [inwx/ansible-collection#13]
Hey ho,

Just tried your collection. without success. :)
I think it is an helpful collection, unfortunately not for me - at least for now.

Anyway, thanks for the ability to manage INWX DNS straight through Ansible!

--
I installed the collection with `ansible-galaxy collection install inwx.collection`

#### Playbook:
```
---
- hosts: localhost

  tasks:
    - name: Ensure A record 'test' exists
      inwx.collection.dns:
        domain: example.com
        type: TXT
        record: test
        value: 'hello world'
        username: user
        password: secret
```
#### Result:
```
TASK [Ensure A record 'test' exists] ********************************************************************************************************************************************************************************************************
task path: /opt/ansible/playbook/inwx_test.yml:6
Friday 22 October 2021  01:02:55 +0200 (0:00:00.027)       0:00:00.027 ********
fatal: [localhost]: FAILED! => {
    "msg": "Could not find imported module support code for inwx.collection.dns.  Looked for either probe_interpreters_for_module.py or respawn.py"
}
```
I am behind a proxy but setting the env changed nothing.
```
---
- hosts: localhost

  tasks:
    - name: Ensure A record 'test' exists
      inwx.collection.dns:
        domain: example.com
        type: TXT
        record: test
        value: 'hello world'
        username: user
        password: secret
      environment:
        http_proxy: "{{ http_proxy }}"
        https_proxy: "{{ https_proxy }}"

```

#### System:
```
NAME="Red Hat Enterprise Linux"
VERSION="8.4 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.4"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.4 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.4:GA"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.4"
```
#### Ansible:
```
ansible 2.9.27
  config file = /opt/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Aug 12 2021, 07:06:15) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
```

If you need any more information - i will try to provide them.

Thanks in advice.
