### ISSUE TITLE
Deleting record not working?

### ISSUE THREAD

**Issue by raidenii** [inwx/ansible-collection#20]
Hi,

I'm using the latest inwx module (1.3.0) from Ansible galaxy but seems deleting records is not working?

A sample playbook:
```
- hosts: localhost
  vars:
    domains:
      - domain1:
        tld: "my.domain.com"

  tasks:
    - name: delete acme challenge dns
      inwx.collection.dns:
        domain: "{{ item.tld }}"
        type: TXT  
        record: "_acme_challenge"
        username: "username"
        value: "removed"
        password: 'somepass'
        state: absent
      loop: "{{ domains | flatten(levels=1) }}"
```

If the parameter does not specify `value`, the module will return a
```
 "result": {
        "api_response": {
            "code": 2005,
            "msg": "Parameter value syntax error",
            "reason": "The given parameter value for 'content' does not match the expected parameter type 'text1024'",
            "reasonCode": "The given parameter value for 'content' does not match the expected parameter type 'text1024'"
        }
    }
```
which does not match what the documentation said - when state is `absent` it should not need a `value`.

But even with `value` defined, it returns `changed = False` and the TXT records are not deleted. Also tried `record: "_acme_challenge.my.domain.com"` but still the records are not deleted.
